import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../../../../../../app/constants/app_spacing.dart';
import '../../../../../../core/l10n/generated/app_localizations.dart';
import '../../application/compliance_notifier.dart';
import '../../domain/entities/compliance_entry.dart';
import '../../domain/failures/compliance_failure.dart';

class ComplianceEntryDetailPage extends ConsumerStatefulWidget {
  const ComplianceEntryDetailPage({required this.id, super.key});

  final String id;

  @override
  ConsumerState<ComplianceEntryDetailPage> createState() =>
      _ComplianceEntryDetailPageState();
}

class _ComplianceEntryDetailPageState
    extends ConsumerState<ComplianceEntryDetailPage> {
  late TextEditingController _refController;
  late TextEditingController _reminderController;
  DateTime? _expiryDate;
  bool _isSaving = false;

  @override
  void initState() {
    super.initState();
    final asyncState = ref.read(complianceProvider);
    final state = asyncState.value;
    final entry = state?.entries.cast<ComplianceEntry?>().firstWhere(
      (e) => e?.id == widget.id,
      orElse: () => null,
    );
    _refController = TextEditingController(text: entry?.referenceNumber ?? '');
    _reminderController =
        TextEditingController(text: '${entry?.reminderDaysBefore ?? 30}');
    _expiryDate = entry?.expiryDate;
  }

  @override
  void dispose() {
    _refController.dispose();
    _reminderController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final asyncState = ref.watch(complianceProvider);
    final state = asyncState.value;
    final entry = state?.entries.where((e) => e.id == widget.id).firstOrNull;
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;
    final l10n = AppLocalizations.of(context);

    ref.listen(complianceProvider, (previous, next) {
      final failure = next.value?.failure;
      final prevFailure = previous?.value?.failure;
      if (failure != null && failure != prevFailure) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              failure.when(
                serverError: (_) => l10n.errorServer,
                unableToCreate: (_) => l10n.complianceUnableToCreate,
                unableToUpdate: (_) => l10n.complianceUnableToUpdate,
                unableToDelete: (_) => l10n.complianceUnableToDelete,
                notFound: (_) => l10n.complianceNotFound,
              ),
            ),
            backgroundColor: colorScheme.error,
          ),
        );
      }
      final success = next.value?.success;
      final prevSuccess = previous?.value?.success;
      if (success != null && success != prevSuccess) {
        final msg = switch (success) {
          'updated' => l10n.complianceUpdated,
          'deleted' => l10n.complianceDeleted,
          _ => success,
        };
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(msg)),
        );
      }
    });

    if (entry == null) {
      return Scaffold(
        appBar: AppBar(title: Text(l10n.complianceEntry)),
        body: Center(child: Text(l10n.entryNotFound)),
      );
    }

    return Scaffold(
      appBar: AppBar(
        title: Text(_typeLabel(entry.complianceType)),
        actions: [
          TextButton(
            onPressed: _isSaving ? null : _save,
            child: Text(l10n.save),
          ),
        ],
      ),
      body: ListView(
        padding: AppSpacing.paddingLg,
        children: [
          if (entry.source == 'auto')
            Card(
              margin: EdgeInsets.zero,
              color: colorScheme.secondaryContainer,
              child: Padding(
                padding: const EdgeInsets.all(12),
                child: Row(
                  children: [
                    Icon(Icons.info_outline,
                        color: colorScheme.onSecondaryContainer),
                    AppSpacing.gapHorizontalSm,
                    Expanded(
                      child: Text(
                        l10n.autoGeneratedFromProfile,
                        style:
                            TextStyle(color: colorScheme.onSecondaryContainer),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          AppSpacing.gapVerticalLg,
          Text(l10n.complianceType, style: theme.textTheme.titleSmall),
          AppSpacing.gapVerticalSm,
          Text(_typeLabel(entry.complianceType),
              style: theme.textTheme.bodyLarge),
          AppSpacing.gapVerticalLg,
          Text(l10n.referenceNumber, style: theme.textTheme.titleSmall),
          AppSpacing.gapVerticalSm,
          TextFormField(
            controller: _refController,
            decoration: InputDecoration(
              border: const OutlineInputBorder(),
              hintText: l10n.enterReferenceNumber,
            ),
          ),
          AppSpacing.gapVerticalLg,
          Text(l10n.expiryDate, style: theme.textTheme.titleSmall),
          AppSpacing.gapVerticalSm,
          ListTile(
            contentPadding: EdgeInsets.zero,
            leading: const Icon(Icons.calendar_today),
            title: Text(
              _expiryDate != null
                  ? '${_expiryDate!.month}/${_expiryDate!.day}/${_expiryDate!.year}'
                  : l10n.notSet,
            ),
            trailing: const Icon(Icons.edit),
            onTap: () async {
              final date = await showDatePicker(
                context: context,
                initialDate:
                    _expiryDate ?? DateTime.now().add(const Duration(days: 30)),
                firstDate: DateTime.now(),
                lastDate: DateTime.now().add(const Duration(days: 3650)),
              );
              if (date != null) {
                setState(() => _expiryDate = date);
              }
            },
          ),
          AppSpacing.gapVerticalLg,
          Text(l10n.remindBeforeDays, style: theme.textTheme.titleSmall),
          AppSpacing.gapVerticalSm,
          TextFormField(
            controller: _reminderController,
            decoration: const InputDecoration(
              border: OutlineInputBorder(),
              hintText: '30',
            ),
            keyboardType: TextInputType.number,
          ),
          if (entry.source == 'manual') ...[
            AppSpacing.gapVerticalLg,
            TextButton.icon(
              onPressed: () => _delete(entry.id),
              icon: Icon(Icons.delete, color: colorScheme.error),
              label: Text(l10n.delete,
                  style: TextStyle(color: colorScheme.error)),
            ),
          ],
        ],
      ),
    );
  }

  Future<void> _save() async {
    setState(() => _isSaving = true);
    final state = ref.read(complianceProvider).value;
    final entry = state?.entries.where((e) => e.id == widget.id).firstOrNull;
    final bpId = entry?.businessProfileId;
    await ref.read(complianceProvider.notifier).updateEntry(
      widget.id,
      referenceNumber: _refController.text.isNotEmpty
          ? _refController.text
          : null,
      expiryDate: _expiryDate?.toUtc(),
      reminderDaysBefore: int.tryParse(_reminderController.text),
    );
    setState(() => _isSaving = false);
    if (bpId != null) {
      await ref.read(complianceProvider.notifier).loadEntries(bpId);
    }
    if (mounted) context.pop();
  }

  Future<void> _delete(String id) async {
    final state = ref.read(complianceProvider).value;
    final entry = state?.entries.where((e) => e.id == id).firstOrNull;
    final bpId = entry?.businessProfileId;
    await ref.read(complianceProvider.notifier).deleteEntry(id);
    if (bpId != null) {
      await ref.read(complianceProvider.notifier).loadEntries(bpId);
    }
    if (mounted) context.pop();
  }

  String _typeLabel(String type) {
    return switch (type) {
      'tax_registration' => 'Tax Registration',
      'trade_license' => 'Trade License',
      'business_registration' => 'Business Registration',
      _ => type,
    };
  }
}
